[profile.default]
src = "src"
out = "out"
libs = ["../../lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = false
fs_permissions = [{ access = "read", path = "./" }]
remappings = [
    "@openzeppelin/=../../lib/openzeppelin-contracts/",
    "forge-std/=../../lib/forge-std/src/",
    "@protocol/=../protocol/src/"
]

[fuzz]
runs = 256

[invariant]
runs = 256
depth = 15
