[profile.default]
src = "src"
out = "out"
libs = ["../../lib", "../protocol/src", "../issuer/src"]
solc = "0.8.24"
allow_paths = ["../protocol", "../issuer"]
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = false

remappings = [
    "@openzeppelin/=../../lib/openzeppelin-contracts/",
    "forge-std/=../../lib/forge-std/src/",
    "@protocol/=../protocol/src/",
    "@issuer/=../issuer/src/"
]

[fuzz]
runs = 256

[invariant]
runs = 256
depth = 15
